[general]
import = [
  "~/.config/alacritty/themes/themes/nord.toml"
]

[font]
size = 10

[font.bold]
family = "Source Code Pro for Powerline"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro for Powerline"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro for Powerline"
style = "Italic"

[font.normal]
family = "Source Code Pro for Powerline"
style = "Regular"

[terminal]

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

